apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:yaHRs1LgOyC6miRbmkWGw0eRKHu8GJMUY+JtKY5rkoz4new8,iv:arNaXyepNhT7cnOFuxfWcjTxy3YECgcfEOWxtMRYNbc=,tag:aP4uDgRgYn4Cnr0vThUSpw==,type:str]
    credentials.json: ENC[AES256_GCM,data:J4gUDhHRG0bfVHBbtuts8D8mxdJsJmW/qJdWTw7kQ1FnDlJeG9bWZ6u/v1Na+BfbbSlYfp6zbsAI721GOytCJhibfsDZ03C25aWZcyxmH1wHYsmCGJ8wbvKmHCUAqYYYp0prPpqHwL/5SWp844tN44G6T8CscMIxgdfN54rY/PyOnPcTFuTdB41L4WAmjmh1t7UJzSV4z9onxXITJwlG81Zf3SBJKYZRUTMoVTmFGw==,iv:QylcSfucuj7zi7DvrMYd3d5zCEv6eEuJHhYh2qB2Wk8=,tag:Ho3TiaI1VZM8SnVq8zkqtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr4f87cnzvmmrvlckn09slf42tsdqzpyukr7crw9yuhtv87kefeq6d6s0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSGh4K1BBR0hNaVl6aUJw
            UW5TQy84eThmNG1nYjh3Z3dJUUd0ZW9EWkM4CmFhc090Y0VxNnczUUdkR2FxeGRr
            cmx3Wkpyb3licU9wTFdhVlhoUmQ3b3cKLS0tIFJxbkVySWRIVm0xYSsxTm9JMmJY
            MlAzZzlYVEJHNmZ4TXZTK2I2c1BVR1EK8xCYEvl/RfMvM5JaxDi26lxDtHal9CxR
            K07nT8+4ILpPNd/OPxquND8/CXGyoqMT4xczy8cKHJFZxPkhVthRbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T23:33:39Z"
    mac: ENC[AES256_GCM,data:7PyZNyS/5OGxO6xpgndI7VCK5y54PAjyoR79gnCoz+UqF0lg9zF28M5TDmIo8zQ1AQB8mj/QgiNeAUA0KEisBlaviFP+HokBigHukJWbCmLKVQ/RR95pJ3YRif5MYgq1w4MIPArLqIDd5dGZuq60er42HrLlWhfEiV28kHok5Rg=,iv:lka0lTeNge68eTPDk0ifOF7H1mWEPofQU2s8HvoEac4=,tag:dBFvEPSD2nqnJnENdRSDcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
