apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:XxgKhQg0qQ28Z4AJ11xTpzNsBiGIYYIPWdWHs5G48QB+GRJj,iv:rmVVYy6WqVnH4bDsA1j1gppYvRG74RPF/TjEC+udQfw=,tag:8PvUaDiFAePtM7Gdwy1IjA==,type:str]
    credentials.json: ENC[AES256_GCM,data:TfxjzMnXK3uVtA16C4+xCMDAqIfnoBIA6fPQhNvm+JtV1trRmqwR+0ASH1aADpqWRvN1Xpmnp8ZQSdAaUVSD17WliJcxoygh2kQPfwQuAel70JGgxpem8DfPwmD/qfgZ8VzQXfV0+8skctmYoIKRgDvPBbp5KAhpsoLEBww/bVr9JQeMAdVjeM9yqgkdJsWoJs1Q3H/ILLM8wM7zVfOAMn0L1BuqxTpJUM711ROqmQ==,iv:vSolPWNsRi2XAr7jt48zFm8z5OIGbzjuHzZbGAgcwBY=,tag:ckEuBt52Tk2jchCzFaoHJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr4f87cnzvmmrvlckn09slf42tsdqzpyukr7crw9yuhtv87kefeq6d6s0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQlhPL0RGaTJrbEw0R0Zm
            b0FPTElKM0haeG5YZGRSc25GRnhnTWRxcUFjCnJqZGFOMkRtWjB6NHBKN2JkZ3lo
            YVJvM3FzWlErazhCWEVaYm9CNkNsSDAKLS0tIFRBQnlBTWxzbmRZS0ozWkRlWUYr
            K0ZGdkVFRXhCSHBZc0JYTldBdHozU0EKHKvffe5ZdMXg10hzbWy+OZmnXnaKdO1C
            GMnbnf+LaDvYZWVYG1KSsXhLkwPlZuHCd9mP2AD064Kx4IhK+mG1PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T20:59:00Z"
    mac: ENC[AES256_GCM,data:RmJovn55fjlDIhwgGhlx3aPGB6pntg02rAUwkmdPE6gQvdQU8CQFCn/iHwMpKKf8oory+6jVxfY+RetwJVIPV2thHL/iCrlU6YzbmMIbzgXAWU/A2fW7oxFuELiT3bJ1u86bwE2xFaPck7FHflbq2wsVBi5IDiFQfR2ss0cYuZo=,iv:4m4oIud+H/AHWH/VzIwFU6yaKiCfGCvy4PZcTwvlNRA=,tag:TTgi6Jza6leo/REjYzybhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
