apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:pYcAB/mZEZGGft9dJynTeT+Dh9qU4kkmVeGDIGASB0E0g9NyI7Bh/g==,iv:4an20gnXELdvgQ9NeZXshB9DeEmUWVLMHiezxfedhc0=,tag:TeK+J2DzUGAfiujtdKTs6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr4f87cnzvmmrvlckn09slf42tsdqzpyukr7crw9yuhtv87kefeq6d6s0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYW5xQnpTdzhLYkZ1THVJ
            R3J5TXdnQndqTUlNemRkRTEwdWJ3Wk84aEdRCkNPQm42WHNxOG5ZTWtlUHhkWm56
            b1hWYVAzQXp3VVZtcldVWk9mWUV4ak0KLS0tIEJ4eXdTN2sxNzIyQlpOMkx4Uk1M
            Wjg3eUtZZVZrN1FxKzZCcy8yTVc2eWcKYbwHeH8/wB/KsQahP2w05B5lAGbT1+tx
            XD5ANq64/YxzZTkZl5es4Ug5oQfU2gRlY8mbzEK76i9PiBq9aqGxOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T23:27:12Z"
    mac: ENC[AES256_GCM,data:e5bzg7BngLql3kwzEXJVVvNAwgNtENJ68josOdRWiNZuBk49TwEVUEhHD/5F0mR9KFY1bjA9z7XYJfimz1ZmGfUGMR2p+GAI9prQxUBqCdYYawd6cMBhzMmXNZ/HWWKftftcA9Bpab1GgqqmhZdFj9VwahOBpKk3GW9DnlM1eWE=,iv:Rh3NbQIbCIX10qNY5zroRT/OB00UDATl5IrLSv8WC5w=,tag:93ATPNjiivG9wdZV+neD9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
