apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:aRoHWE2T7KkYj04hbe+UYh4B9eyebyrKIu6LKEJIe7yHDmGHG4uPig==,iv:/4TfK3hUQ8Sz+KOtBErjxBJeVImHNfM1oUe0j99AE1I=,tag:QHTBoV9KKw73+uiHYJ8okg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr4f87cnzvmmrvlckn09slf42tsdqzpyukr7crw9yuhtv87kefeq6d6s0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdVZiZFBFVytpTE1MZGxB
            d05Ja1RYYWNHYkFPcE53aWtzNjE3SG1IdEFBCjk3S29YNDNWMjgzTEFUSForNlhC
            Q0ZWQmxlQjlXSnFCOVhxaGlTU0UyUlUKLS0tIGR2c3VOdS9WTUk3dWRZUmx3MlUy
            a1I1cTUyTnp4L0dFaWFteVlOdzlGWUUKki67mbWE/yn8oyBXwjRbwkSiixa7LFO3
            eRickmrA+ybEFuxMF/VQY+wVZ2NSHq9WwJnBH5tdCKokNe+ub/HWew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T23:33:39Z"
    mac: ENC[AES256_GCM,data:gR+S38LqeRhDi5rCTEDr/I5MnW/JcBupCjix+oaqMa06gxmeWqf3jqFRS6xB3oqvHpK8EkvKopkhf1rzJVIaGZnVemqbHJGAFd4zEQVvhmAK+Mc/tbdmZPuokr75inE2MhlWHIBSklOFwv2j3l1ASsubrevCb4ESM/HuGd/SXBM=,iv:MWyp8uFqC0pyDIN/77aNNeHU01jo2gJ6ngFSM8uNlWg=,tag:eorDGqGD3q9u6Uo1vFRHBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
