apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:jguBsn4VjOO/OkwuxnBxiegFCXiI3ygAQfxqKH3gOLm3X9v5290NaA==,iv:Lct4v0Bw66V+M8g0thOf59HtO0fW2raIH8RrlzI5Jo8=,tag:tJQlsHoUvVlT6UplKeLKvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr4f87cnzvmmrvlckn09slf42tsdqzpyukr7crw9yuhtv87kefeq6d6s0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRUVZbVBFMUxqakJUT1Ro
            WG1VRFcwcjNzcGRTM0FzeHhLUU5KeGpVSTE0CjJJNTVHQmZUdEFNOWgwTVJMMGhI
            S042bW1tSjlGQkc1K2hsM2dYenk3Q2sKLS0tIGZEckgyY3owRng3WllhZHNoWnQ2
            dG9Hc3hMc3ZUb0xyU3p3VEo1QWRlMFUK/vr+yJCL8xe4LN8GmyVa12zsnvBaRTNt
            3qZ1hK5Lf8G4Af11xM1LNsElPtVcnUiRaPf6MWhUyCbRXGhCrI49OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T09:33:24Z"
    mac: ENC[AES256_GCM,data:h+inhGg4ozA+B74Jam/h88iC68mLBcwjgt1T0rFhY/khgL0zZClSrkgLWIlFsCJihzV+tcOi3qqm04krEOUhZHNtOJDpYlxazEB4Sr5Qudi6rUAqaXR3noTaAi2qO61VQMHWEe6/kwbDQ0Cb3npCYwvc/fzAMKmCTb+qkeTi8JM=,iv:ju80E3larW0YaYjHwRQNmJv4QiBHS6PSSow27xVuhEI=,tag:h35mFKan1Mb9c8bOkygXiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
