apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:FMNmBnqPm2QMAet6lC4fTtrrpCuOFAzAiA7twh2hCwSi7gw0OcCmFg==,iv:SPdVQR/mRRvLnJIb+2UtoGOc5XVFHdlIt5BHZgnmZ2Q=,tag:/Pb81qDipplhxN4rtz+9sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr4f87cnzvmmrvlckn09slf42tsdqzpyukr7crw9yuhtv87kefeq6d6s0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MkwwN0xjU0o1RFF6MDBJ
            UmxIaUgxWklCbHBFa3lONThhVHNrZGkwOVJnCmpXLzl3RFhwc3lhdHc1MUIyM0tG
            OHUrcnhpVnZPRjVva0RSZ0NlL1pRUnMKLS0tIDR6dmxaNExmT2J3RG9NM2p2NW5M
            SXl2cXRUK0xGKzFaU0hWYmRGR0hjelUKgKi1agFf7jhbA0qwFsMYUYIfKdaGfrfz
            rCFGFTgAYtT2Whrc5oE077b6S9wlhdEsZm+b/wlH/tJA2L3EvzaoQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T23:55:28Z"
    mac: ENC[AES256_GCM,data:kJSGVJ4sJsUcov0lsTcZvWk0p0eE5vPapTM1PgqtdpHZV1yYTy0UMg4gUG5oZToGKdrPBbjBPC7OrIinrjlxt+OGMGhQm5dZVH32s1URHMrY+I0cfZquM5v1RwFjy8moFtpxLJ7f5UwO9L902PKdUxqc4AGaNOw+8qPqwkyWGh4=,iv:arxqcsHDWTOPhMId6mj2QXk5sa06ZpAEAWJlZbXFFI8=,tag:C+51cHsc4VSFQz9jL1OzBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
