apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:MOyAbkSPc9pXvgSSUzY=,iv:aJwgEbmShTIaeK004ljVvjm1UwQTVN3JgPD8Sn2KrQo=,tag:zaicNccjUFq5ExzwK/qaCg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:kUIAIjBesuZQZH+9AcD4eqvI4f+nrw==,iv:WO0Ujq1l89bIcnCq4jSCJNbH/K6hRtKV+j3xJlKbPEM=,tag:YO+SFcaMdRBHCHHfn/xE7Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:lT3aTPS1VQoRezQMwbyMMvyaq6gkOBG58jfEYrfriF12pCxq,iv:GdoMiqM5NmPxD0tpqnwdLM+kyLn41UbmBS7N4aODo3M=,tag:5x2coH68EDTlsKSMSwKcrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr4f87cnzvmmrvlckn09slf42tsdqzpyukr7crw9yuhtv87kefeq6d6s0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQmFLemI3M2ljZFhZOUZZ
            SmlRM3N6R05YaDlXS1l3N0dxL3ZnQ2c3Z1VNClluZ3R5cWRmV0F4RHhNNmV4REZZ
            elRQUUJ0NVp4RHIwZ2dNa0twUFZocGcKLS0tIFB5STFFZFVPWXlEL05sNGNEemZj
            WWpVUVhudUxlRFB5dSs0WG5FV3FBMlUKCXYh7aX8hdh7hKWycFrTfIDPZ0GO8L+1
            mTnr1xrkLVS7e+zpTgrEtOvLgX/xY3gENbtBV9+Xs4F7bLM6xpsAuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T20:59:00Z"
    mac: ENC[AES256_GCM,data:xNB8/ab/aekRP8Q2lQf05AYAbCu35RzZ+il04FBiVnlOc2YdFQ8RU4ZoyIZcyNjsmhcWIjU11S4lnHTW/ujxh9cODLeXeXJAKjubB/yEjRThU3j6SymRazdLPfHBQcOS0XeMGuV5hB8IGlHhDgu5YSMz5a5t0r4r5e4Ha59QKIw=,iv:e1nWWAJw05L/x8+DyWnWzZH0mERk8zQ5/zv6A8D1+aE=,tag:oHkFbJWrakcKEXapeKxOuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
