apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:+SABs9Zihasy7C5FFzQ=,iv:9cTKVfJgZvidLGixYaH6lFrx2ZXq8UGjI9Q1jzq1Vhk=,tag:daBvli7yLHdSvB0S8eE/5A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:QPIy6D6jRpCMKBjA3fn/fj56lE5+FA==,iv:8bGTeSOpSW9NAt77WQw9WmrJpLZ8MgWm2qzyREr7Q34=,tag:QpsJVc9cke/B78dLnkcLwQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:q+btyibGfASKAQUNG63sPG4TSHIfhA/xWcU+e9K3tZY2ZVRF,iv:dA2cwFxhEaU/VmhRftLWaQDgtRnjAMQKVFSRhNbaA8w=,tag:uUxIyvMIq+hALzIFFLlqOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr4f87cnzvmmrvlckn09slf42tsdqzpyukr7crw9yuhtv87kefeq6d6s0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCckcrbTBvMk0rUW42YXBM
            eW1yVjJZSUh1K05CaXF6K3piOENTNjQ1aFY4CmpoeDVWUkFxeUFDcmxBRDJqbWZm
            c3JWWFJvSmFxMTUyUGdrTTB1T2MvOFkKLS0tIHQ0bmpaVm93bjViaGd0YmZGMUlx
            WGYrRTRaM1N1UXdFQTBEQ1pFSUovR3MKPV8gF0X2vsz2vkW6Tv59k/KC1GGOOLu2
            WI9aRqCaq50H0TsCzVGXqC80+ViF6sbKy9xazLgUW2rGMkO0CpAvTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T23:55:28Z"
    mac: ENC[AES256_GCM,data:UJUrjrAV1nMVteWL4d40/J6xvPwLQaUpk9v1zf8BN/ZP4QBhjiyVsyltYQgD8pbuqCfakqF//ESq+C/Ol+zA9ICutQx+47/Uz+BBXbTw93Co00cHMOgecJbKkyqbkRvwH0m5BYE+Hk1i4Qdsv4AZhGo8Fv4TjPyhe9Y6kVfn5a0=,iv:IOUSyr5DuENL5+7ZhKyin0p3GCqfkzrpr1R/hqDOISs=,tag:4BGIDs+AmCI9s3ru2F7a8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
