apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BB3SYkOf+o81ff8NqjI=,iv:a8SwRFscTXWOHYCnAliw0jbWELx08kVh4SI6Fak7FrI=,tag:9onjwTbHwWjl76+x/smdOA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:rW1OAnrvHXRjLL/E4Db8grE2u7JDJQ==,iv:mOfmkhiQUUZeRWMCGc3CTWDvQDdiuabStTO9iIsPhCE=,tag:hskftBMNctZCBfw9ECGyPg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xAwMQnZ2d8vWGB+N6I3CAV+l9LcOyq0dUolFv4comlIIMDnw,iv:r+ODqpJqcAYSOfwg6xKP+Bmoo3egqhQBB69qie4/2Uc=,tag:g2PR/OUwga/VE4winjmhlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr4f87cnzvmmrvlckn09slf42tsdqzpyukr7crw9yuhtv87kefeq6d6s0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMzVGWUNrTFF3Nk4zSkNR
            SVBjZVB5SHlRR09aeFBPUThnM2M1cFJOMkd3Cms2aDREcWtIMlZUUXUzT3NXRmVC
            VUZtOEFVckxaejJXZ2pydzk3T1pyaXMKLS0tIDNKMnd5YW0yL011b2Q4VXp6Y1Vp
            Nkl4K2JzWXFwOFR3NHNMdU90aTkvL3cKOGWufcs+GkKLFmGIrHzwWwbS8CvXQmjl
            ckVVLqXRHZzwfXsV7v1JAF1VPqCClNAbONJ6lEkJYqekc/FbRWjDAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T22:40:10Z"
    mac: ENC[AES256_GCM,data:Mx/HEh0x2/mbwVAxxOI4weucFN8O5EggXGofOo2D9iJFDag8cdI7bAsJvbe8ySSw7Ki5YIlLE8ITAFzk5I949/BzO0msuE3o5HOJ1n3zh3LkWhHs61ge8l3V4oiO0Se+Cwxsi+9WRdKNmtaQRpf2SFL7hyi+Y0e+WSqLZBrSyUM=,iv:/AeyBzPgMlytmB2sX8kWH7uHeXo3jHLthSHv5stxz48=,tag:R13SQOwk/0LqAU5YI2KN+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
