apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Ko+mSmg5YoJESet2Zs5JIl7dPBP/+nC4xW3dO5Zpb6k=,iv:s8DP7MdQxRRqcvFF7yvOYIgpKTT1X20QTS/7DFlZWmg=,tag:qcH+Qkzkm8KOyQoLea5L3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr4f87cnzvmmrvlckn09slf42tsdqzpyukr7crw9yuhtv87kefeq6d6s0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYUlLazhIWWlOQ3FnNHY1
            Nzl2MmNLblJtNWJEL0NnSkdQR3l5dUJwWEg0CmNTM2p1SUNiTGlMQTF6OTVpQ0dw
            aTc2dlM5eWtWcnl0TCtkNU1qMEFyQzQKLS0tIHhaWjk2UkIwSUhwWE40cHV1bmI4
            RktXNkI0RG9hd3hXMWNsZEd5M3VURnMKVhZPYDR+frtMrXlMrxBazvXqYczEnXiU
            h38bFMcERWE4Tw5fxeRrFHxrfOF8VoU1vLiCmk0KKthF6CDDRYHsZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T22:40:10Z"
    mac: ENC[AES256_GCM,data:3HDflCXm+BvVuqOi4Fx91QJmOYUM3kswreM4vrI35Gq+jlUBBgjBEQblLkVEuR4s6tklPhzuZETOB3jwactw3ai549MCLsj6RSOlPt5UyDrgF+nHHv+m2wavUVNPVkpgpar89vZgGr+JiUuOyG93n5wbGKramQEE6cMNuO5zkEE=,iv:i2QSjkV1y71/ORn4BnCayK3xw3aDdl6K0fU1ZYIBMwg=,tag:SwWIJ+fCU9QayIHF4Zw1Jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
