apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Rv3pmroSUXFAuLIxFHw1bWd2CqUX+8y3o1YlH3bv1F4=,iv:FI7RF6Kn2klkcblUmqXCbvp0/VLkUcqPeC6dYEKJlzw=,tag:PlEBRTW9Aafad9BaFAGLMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr4f87cnzvmmrvlckn09slf42tsdqzpyukr7crw9yuhtv87kefeq6d6s0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNXB4RmJQNnV0WnNQdm16
            c250Y3dycDJMcHNFZU02RSs0K3VOMDZUVFZFCkJhL3kyelpqUDAxR2czZmNsQlls
            VjNjU0NlY040U2tvVWJEbnEyQ3lPTlkKLS0tIFdFanIraS9uemxBdVJyU0hQS1lq
            YnVzaVZqenNvb3VjdjJQaEQxOHplR3MKppAneVIdZdM5uKHLvflfhl8tty9T3yhe
            sDOtYX73xOdPMfYm3tqp+TEyqi9G1yBdz0gXfyYwG5dJ9cJxy1SCtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T20:07:06Z"
    mac: ENC[AES256_GCM,data:22NYMM6S/YuMxQheS4mkWxzdxHNRPWa0qScYmoPNSCWWRN2rmnfO3q8/Et+U9vyn7UYKU/ZN5khtHM55eHGNrx8rldtkEIRTK7xUczbkFgiOeze1AjrnNwhrbpcmfREwtlhOtcx9+42ZoNiK9NKV0oRW/OPf/9F+NDV0qRNcFzM=,iv:8cZHrhreNhamaT/9ekbHr2hy3bYVNnJxgc20ykKYYe8=,tag:eaR1ptUv4sO/OVWBNtIGMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
